package stats_shared

import (
	"context"
	"fmt"
	"log/slog"
	"strconv"
	"strings"
	"time"

	targetsv1alpha1 "github.com/willmurnane/clusterfuzz/api/v1alpha1"
	corev1 "k8s.io/api/core/v1"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

type ReducerType int

const (
	AnnotationPrefix             = "fuzz.will.murnane.family/"
	SUM              ReducerType = iota
	MAX
	MIN_TIME
)

var (
	// Things we know how to aggregate, with comments giving typical values for the fields that we don't yet.
	Reducers = map[string]ReducerType{
		"start_time":  MIN_TIME,
		"last_update": MIN_TIME,
		// run_time          : 60
		// fuzzer_pid        : 336
		"cycles_done":     SUM,
		"cycles_wo_finds": SUM,
		// time_wo_finds     : 1
		"fuzz_time": SUM,
		// calibration_time  : 3
		// cmplog_time       : 5
		// sync_time         : 0
		// trim_time         : 1
		"execs_done":        SUM,
		"execs_per_sec":     SUM,
		"execs_ps_last_min": SUM,
		"corpus_count":      SUM,
		"corpus_favored":    SUM,
		"corpus_found":      SUM,
		"corpus_imported":   SUM,
		"corpus_variable":   SUM,
		"max_depth":         MAX,
		// cur_item          : 671
		// pending_favs      : 0
		// pending_total     : 207
		// stability         : 94.87%
		// bitmap_cvg        : 26.31%
		"saved_crashes": SUM,
		"saved_hangs":   SUM,
		"total_tmout":   SUM,
		"last_find":     MIN_TIME,
		// last_crash        : 0
		// last_hang         : 0
		// execs_since_crash : 690193
		// exec_timeout      : 20
		"slowest_exec_ms": MAX,
		"peak_rss_mb":     MAX,
		// cpu_affinity      : -1
		// edges_found       : 4013
		// total_edges       : 15253
		// var_byte_count    : 206
		// havoc_expansion   : 0
		// auto_dict_entries : 96
		"testcache_size":  SUM,
		"testcache_count": SUM,
		"testcache_evict": SUM,
		// afl_banner        : /target/amd64
		// afl_version       : ++4.34c
		// target_mode       : persistent shmem_testcase deferred

		// unusual case: stats-timestamp is generated by us, not the fuzzer.
		"stats-timestamp": MIN_TIME,
	}
)

func Reduce(name string, raw_values []string) string {
	reducerType, exists := Reducers[name]
	if !exists {
		slog.Warn("No reducer found for stat", "stat", name)
		return "error_no_reducer"
	}
	switch reducerType {
	case SUM:
		var s = 0.0
		for _, element := range raw_values {
			value, err := strconv.ParseFloat(strings.TrimSpace(element), 64)
			if err != nil {
				slog.Warn("Invalid value for SUM reducer", "stat", name, "value", element, "error", err)
				continue
			}
			s += value
		}
		return fmt.Sprintf("%.0f", s)
	case MAX:
		max := -1.0
		for _, element := range raw_values {
			value, err := strconv.ParseFloat(strings.TrimSpace(element), 64)
			if err != nil {
				slog.Warn("Invalid value for MAX reducer", "stat", name, "value", element, "error", err)
				continue
			}
			if value > max {
				max = value
			}
		}
		return fmt.Sprintf("%.0f", max)
	case MIN_TIME:
		min := float64(0)
		var min_index = -1
		for index, element := range raw_values {
			floatValue, floatErr := strconv.ParseFloat(strings.TrimSpace(element), 64)
			if floatErr != nil {
				chunks := strings.SplitAfterN(element, ":", 2)
				timeValue, timeErr := time.Parse(time.RFC3339, strings.TrimSpace(chunks[1]))
				if timeErr != nil {
					fullTimeValue, fullTimeErr := time.Parse(time.RFC3339, element)
					if fullTimeErr == nil {
						floatValue = float64(fullTimeValue.Unix())
					} else {
						slog.Warn("Invalid value for MIN_TIME reducer", "stat", name, "value", element, "timeValue", chunks[1], "floatError", floatErr, "timeError", timeErr)
						continue
					}
				} else {
					floatValue = float64(timeValue.Unix())
				}
			}
			if floatValue < min || min_index == -1 {
				min = floatValue
				min_index = index
			}
		}
		return fmt.Sprintf("[container %d]: %s", min_index, time.Unix(int64(min), 0).Format(time.RFC3339))
	default:
		panic(fmt.Sprintf("Unknown reducer type %d", reducerType))
	}
}

func UpdateFuzzJobStatus(c client.Client) error {
	// Look for any pods which have the 'app=afl' label
	// For each such pod, look for the 'stats' annotation written by the stats container
	// Look for any FuzzJob instances which have a StatefulSet associated with them
	// Aggregate these stats and write them back to the FuzzJob instance as annotations
	ctx := context.Background()
	var fuzzjobList targetsv1alpha1.FuzzJobList
	err := c.List(ctx, &fuzzjobList)
	if err != nil {
		return err
	}
	var podList corev1.PodList
	err = c.List(ctx, &podList, client.MatchingLabels{"app": "afl"})
	if err != nil {
		return err
	}
	// job name -> stat name -> list of values
	latestStats := map[string]map[string][]string{}
	// Iterate over pods, find which statefulset they belong to, and find which fuzzjob that statefulset belongs to.
	for _, pod := range podList.Items {
		parent := pod.OwnerReferences
		if len(parent) == 0 || parent[0].Kind != "StatefulSet" {
			continue
		}
		statsForThisJob, exists := latestStats[parent[0].Name]
		if !exists {
			statsForThisJob = map[string][]string{}
			latestStats[parent[0].Name] = statsForThisJob
		}
		updatePodStatsAnnotations(statsForThisJob, pod.Annotations)
	}
	for _, fuzzjob := range fuzzjobList.Items {
		// Now, for each fuzzjob, aggregate the stats from its pods and write them back to the fuzzjob annotations.
		status := map[string]string{}
		statsForThisJob, exists := latestStats[fuzzjob.Name]
		if exists {
			for statKey, updates := range statsForThisJob {
				aggregatedValue := Reduce(statKey, updates)
				status[AnnotationPrefix+statKey] = aggregatedValue
			}
			// Update the fuzzjob status
			fuzzjob.Status.Progress = status
			err = c.Status().Update(ctx, &fuzzjob)
			if err != nil {
				return err
			}
		}
	}
	return nil
}

func updatePodStatsAnnotations(statsForThisJob map[string][]string, annotations map[string]string) {
	for k, v := range annotations {
		if strings.HasPrefix(k, AnnotationPrefix) {
			statKey := strings.TrimPrefix(k, AnnotationPrefix)
			statsForThisJob[statKey] = append(statsForThisJob[statKey], strings.TrimSpace(v))
		}
	}
}
