name: Gitea Actions Demo
run-name: Build
on: [push]

jobs:
  Container:
    env:
      RUNNER_TOOL_CACHE: /var/lib/docker/
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Build container
        run: |
          docker build . -t registry.will.murnane.family/clusterfuzz:latest --platform linux/amd64,linux/arm64
          docker push registry.will.murnane.family/clusterfuzz:latest
  Lint:
    env:
      RUNNER_TOOL_CACHE: /var/lib/docker/
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Lints
        run: |
          make lint fmt vet
